### ISSUE TITLE
Fehlermeldung bezüglich alkis-ableitungsregeln.sql

### ISSUE THREAD

**Issue by ruhri** [norBIT/alkisimport#13]
psql:alkis-ableitungsregeln.sql:399: FEHLER:  Einfügen oder Aktualisieren in Tabelle »alkis_linien« verletzt Fremdschlüssel-Constraint »alkis_linien_katalog_fkey«
DETAIL:  Schlüssel (katalog)=(1) ist nicht in Tabelle »alkis_signaturkataloge« vorhanden.

**Comment by jef-n** [comment]
Bei leerer Datenbank und ohne create/clean/update im .lst?

**Comment by ruhri** [comment]
hmmm....
DB wurde erst nicht befüllt, nur Schema angelegt, anschließend in einem zweiten Durchgang mit NAS-Dateien im Update-Modus befüllt - hat "historische" Gründe und lag wenn ich mich recht erinnere in den Daten begründet. Werde den Vollimport mehrerer Kommunen aber mal in einem Rutsch starten (direkt bei "create")

1.
PG:dbname=XXX
epsg 25832
create
log
KEINE NAS-DATEIEN

2.
PG:dbname=XXX
epsg 25832
create
log
options --config PG_USE_COPY YES
NAS-DATEIEN
...
.

**Comment by jef-n** [comment]
Beim zweiten Durchlauf auch 'update' statt 'create'?

**Comment by ruhri** [comment]
ja! sorry, typo
