### ISSUE TITLE
./alkis-import.sh: line 522: sql: command not found

### ISSUE THREAD

**Issue by StefanReichel** [norBIT/alkisimport#16]
trying to import xml files as per example nas.lst
nas.lst:

 PG:dbname=alkis user=alkis password=alkis
 epsg 25832
 create
 log
 1.xml
 2.xml
 3.xml
 ...
(but amended correct DB credentials)
and running 
alkis-import.sh nas.lst
returns:
alkis-import.sh: line 522: sql: command not found
I suspect the functional scope of sql() might be too small?!

Where to from here?

Cheers,
Stefan

**Comment by jef-n** [comment]
Fehler ist hier nicht zu reproduzieren.

**Comment by StefanReichel** [comment]
Problem geloest.
Dieser Fehler ist reproduzierbar, in dem man "PG:" in der DB Zeile weglaesst/entfernt. Diesen Fehler habe ich gefunden und behoben.

Darauffolgender Fehler ist

 `RUNNING: ogr2ogr -f PostgreSQL -update -append PG:dbname=alkis user=stefan password=password -a_srs EPSG:25832 /home/stefan/Documents/[...].shp.xml`

`FAILURE:
Unable to open datasource '/home/stefan/Documents/[...].shp.xml' with the following drivers.
  -> ESRI Shapefile
  -> MapInfo File
[...]
`
Wie in issue [17](https://github.com/norBIT/alkisimport/issues/17) beschrieben

**Comment by jef-n** [comment]
Ok, dann ist das aber kein Fehler.  Die PG:-Zeile ist nicht optional.
