### ISSUE TITLE
0 elements input array bei Erzeugung der Böschungen

### ISSUE THREAD

**Issue by marvinkinberger** [norBIT/alkisimport#19]
Bei einigen Böschungen bekomme ich bei der Erzeugung folgende Fehlermeldung:
NOTICE:  0 elements input array
CONTEXT:  SQL statement "INSERT INTO po_lines(
                        gml_id, thema, layer, line, signaturnummer, modell
                ) VALUES (
                        r.gml_id, 'Topographie', 'ax_boeschungkliff', st_multi(st_collect(b1)), '2531', r.modell
                )"
PL/pgSQL function "alkis_boeschung" line 121 at SQL statement

Der Wert für die Variable b1 ist in diesen Fällen NULL.

**Comment by jef-n** [comment]
Wie groß ist die Wahrscheinlichkeit, dass das auch in den OpenData-Daten aus Unna vorkommt?

<pre>
diff --git a/alkis-ableitungsregeln.sql b/alkis-ableitungsregeln.sql
index 9e196a3..fa4c48f 100644
--- a/alkis-ableitungsregeln.sql
+++ b/alkis-ableitungsregeln.sql
@@ -6550,11 +6550,16 @@ BEGIN
                        i := i + 1;
                END LOOP;

-               INSERT INTO po_lines(
-                       gml_id, thema, layer, line, signaturnummer, modell
-               ) VALUES (
-                       r.gml_id, 'Topographie', 'ax_boeschungkliff', st_multi(st_collect(b1)), '2531', r.modell
-               );
+               IF b1 IS NOT NULL AND array_length(b1,1)>0 THEN
+                       INSERT INTO po_lines(
+                               gml_id, thema, layer, line, signaturnummer, modell
+                       ) VALUES (
+                               r.gml_id, 'Topographie', 'ax_boeschungkliff', st_multi(st_collect(b1)), '2531', r.modell
+                       );
+               ELSE
+                       RAISE NOTICE '%: Böschungsgeometrie leer', r.gml_id;
+               END IF;
+

                b1l := ARRAY[]::double precision[];
                b1 := ARRAY[]::GEOMETRY[];
</pre>

**Comment by jef-n** [comment]
Die Wahrscheinlichkeit ist 1.

**Comment by marvinkinberger** [comment]
Ich habe gerade einmal nachgeschaut. Die Daten sind in den OpenData-Daten enthalten.
Du kannst Sie dir über https://www.opengeodata.nrw.de/produkte/geobasis/lika/alkis_sek/bda_oe/bda_oe_05978000_Unna_EPSG25832_NAS.zip laden.
Die Böschungen sind in der "fachinformationen_61001_bda.xml" enthalten.

Wenn du es dir anschaust, es gibt auch noch einige komische Überschneidungen bei den Böschungslinien.

**Comment by marvinkinberger** [comment]
Zum Vergleich kannst du dir auch unseren WMS für die ABK anschauen. 
URL: http://geoservice.kreis-unna.de/cgi-bin/mapserv.fcgi?map=/storage/mapserver/mapfiles/ku_tkKreisUnna_dtk_abk.map
Er ist im Maßstab von 1:2001 bis 1:5000 sichtbar. In den anderen Bereichen werden andere Karten dargestellt.

**Comment by jef-n** [comment]
Einige unberücksichtigte Sonderfälle gibt es wohl noch:
* es wird davon ausgegangen, dass es gegenüber einer Oberkante auch immer eine Schnittkante (Unterkante oder Trennschraffe) gibt.  Das ist aber nicht immer der Fall - tlw. laufen die Oberkanten außen herum und die Senkrechte schneiden nur die gegenüberliegende Oberkante (aber keine Schnittkante).   Manchmal kommt es auch vor, dass die Oberkante mehrfach geschnitten wird bevor die Senkrechte auf eine Schnittkante trifft.
* die Böschungskanten bestehen tlw. aus mehreren Linestrings,
* es gibt Kanten mit nur zwei Punkte, die sie auch noch mit der Gegenkante gemeinsam haben.  Dann liefert `st_maxdistance`, statt einer brauchbaren Maximallänge für die Senkrechte,  `NULL`.
* bei abknickenden Böschungsoberkanten soll es in den Winkelhalbierenden Trennschraffen geben (zumindest habe ich das so verstanden), die verhinden, dass sich bei abknickender Böschungsoberkante die Senkrechten gegenseitig überschneiden.  Die gibt es allerdings in den Daten aus Unna nicht durchgängig.  Daher sehen Böschungen in den Kurven tlw. wüst aus.   Das WMS scheint dann "irgendwie" zu kürzen.
* Der NRW SK ([S. 117](http://www.bezreg-koeln.nrw.de/brk_internet/geobasis/liegenschaftskataster/alkis/vorgaben/pflichtenheft_06/pflichtenheft_signaturkatalog/anlage_06_teil_c2_praesentationsregeln_abk.pdf#page=117)) weicht ab:
  * Der Schraffenabstand ist kleiner (140 statt 600; wobei mir die Böschungen im WMS allerdings nicht deutlich enger schraffiert vorkommen),
  * es gibt Beschriftungen für "weitereHoehen" und
  * allgemeine Böschungskanten (1200) (wie die allerdings mit Ober-, Unterkanten und Trennschraffen zusammenspielen ist mir nicht klar)
