### ISSUE TITLE
Spaltennamen kürzen

### ISSUE THREAD

**Issue by ferengi82** [norBIT/alkisimport#21]
hoffentlich werde ich nicht lästig ;-)

wenn möglich bitte die Spaltennamen kürzen.

Hintergrund:
ich speichere mir in QGIS verschiedene Layer zu offlineverwendung als Shape-Dateien ab.
Leider unterstützt das Shape-Format nur kurze Spaltennamen. Beim Export wird z.B. aus sn_randlinie => sn_randlin.
Es müssen also immer die Stile in den Layereigenschaften auf die neuen Spaltennamen angepasst werden damit die Darstellung passt.

Vielleicht lassen sich ja kürzere Spaltennamen finden.

Gruß
Christian Maurer

**Comment by jef-n** [comment]
Ich würde das Offline-Editing-Plugin verwenden. Das gibt's das Problem nicht (spatialite) und die Darstellung kommt gleich mit.
