### ISSUE TITLE
Fehler bei Update von Datensatz

### ISSUE THREAD

**Issue by tiehfood** [norBIT/alkisimport#27]
Beim Versuch eine aktuelle Version der ALKIS-Daten in die Bestehende Datenbank einzuspielen, bricht der Import mit folgender Fehlermeldung ab:
> psql:postprocessing.d/4_nas2alb/3_eignerart.sql:42: ERROR:  duplicate key value violates unique constraint "eignerart_pkey"|
> DETAIL:  Key (flsnr, bestdnr, bvnr)=([...]) already exists.|

Muss ich bei einem Update etwas spezielles beachten?

**Comment by jef-n** [comment]
On Sun, 25. Feb 2018 at 04:42:58 -0800, tiehfood wrote:
> Beim Versuch eine aktuelle Version der ALKIS-Daten in die Bestehende Datenbank einzuspielen, bricht der Import mit folgender Fehlermeldung ab:
> > psql:postprocessing.d/4_nas2alb/3_eignerart.sql:42: ERROR:  duplicate key value violates unique constraint "eignerart_pkey"|
> > DETAIL:  Key (flsnr, bestdnr, bvnr)=([...]) already exists.|
 
> Muss ich bei einem Update etwas spezielles beachten?

Eigentlich nicht.  Die Ursache ist allerdings ohne die Daten schlecht zu
beurteilen.  Gab's weitere Meldungen beim Import?

-- 
norBIT Gesellschaft fuer Unternehmensberatung und Informationssysteme mbH
Rheinstrasse 13, 26506 Norden
GF: Jelto Buurman, HR: Amtsgericht Aurich HRB 100827

**Comment by tiehfood** [comment]
Die vollständige Log-Datei:

> Import-Version: 7706c16
> Datenbank-Version: PostgreSQL 9.6.6 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.0 (clang-700.1.76), 64-bit
> PostGIS-Version: 2.3 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
> GDAL 2.3.0dev, released 2017/99/99|
> psql (PostgreSQL) 9.2.4|
Gesamtgröße des Imports: 1227MiB
>  Aktuelles Schema alkis.|
> psql:alkis-update.sql:26: NOTICE:  ALKIS-Schema-Version: 16|
> CONTEXT:  PL/pgSQL function alkis_update_schema() line 34 at RAISE|
> psql:alkis-update.sql:26: NOTICE:  ALKIS-PO-Schema-Version 3|
> CONTEXT:  PL/pgSQL function alkis_update_schema() line 15924 at RAISE|
> psql:postupdate.d/nas2alb.sql:96: NOTICE:  ALB-Schema-Version 3|
> CONTEXT:  PL/pgSQL function alb_update_schema() line 16 at RAISE|
postupdate.d\nas2alb.sql ausgeführt.
>  Lade Signaturen...|
preprocessing.d\0_alkis-signaturen.sql ausgeführt.
10 Dateien mit 1227MiB in 1h3m25s importiert (330kiB/s)
>  Koordinatensystem: 31467|
>  Bruchstrichvoreinstellung: Schrägstrich|
>  Niederwertige politische Grenzen verdrängen: Nein|
>  Präsentationstabellen werden geleert.|
postprocessing.d\0_ableitungsregeln.sql ausgeführt.
>  Flurstücke werden verarbeitet.|
>  0 Flurstücke mit abweichendem Rechtszustand.|
>  Bestimme Grenzen mit abweichendem Rechtszustand|
>  Erzeuge Flurstücksnummern in Schrägstrichdarstellung...|
>  Erzeuge Flurstückszähler...|
>  Erzeuge Flurstücksnenner...|
>  Erzeuge Flurstücksbruchstriche...|
>  Erzeuge Zuordnungspfeile...|
>  Erzeuge Überhaken...|
postprocessing.d\1_ableitungsregeln\11001.sql ausgeführt.
>  Besondere Flurstücksgrenzen werden verarbeitet.|
>  Strittige Flurstücksgrenzen werden verarbeitet.|
>  Politische Grenze werden verschmolzen|
> psql:postprocessing.d/1_ableitungsregeln/11002.sql:228: NOTICE:  adfs:{7101} sn:2016 n:0|
> CONTEXT:  PL/pgSQL function pg_temp_2.alkis_besondereflurstuecksgrenze(boolean) line 41 at RAISE|
> psql:postprocessing.d/1_ableitungsregeln/11002.sql:228: NOTICE:  adfs:{7102} sn:2018 n:0|
> CONTEXT:  PL/pgSQL function pg_temp_2.alkis_besondereflurstuecksgrenze(boolean) line 41 at RAISE|
> psql:postprocessing.d/1_ableitungsregeln/11002.sql:228: NOTICE:  adfs:{7103} sn:2020 n:3030|
> CONTEXT:  PL/pgSQL function pg_temp_2.alkis_besondereflurstuecksgrenze(boolean) line 41 at RAISE|
> psql:postprocessing.d/1_ableitungsregeln/11002.sql:228: NOTICE:  adfs:{7108} sn:2026 n:0|
> CONTEXT:  PL/pgSQL function pg_temp_2.alkis_besondereflurstuecksgrenze(boolean) line 41 at RAISE|
> psql:postprocessing.d/1_ableitungsregeln/11002.sql:228: NOTICE:  adfs:{2500,7104} sn:2010 n:5277|
> CONTEXT:  PL/pgSQL function pg_temp_2.alkis_besondereflurstuecksgrenze(boolean) line 41 at RAISE|
> psql:postprocessing.d/1_ableitungsregeln/11002.sql:228: NOTICE:  adfs:{7106} sn:2022 n:18940|
> CONTEXT:  PL/pgSQL function pg_temp_2.alkis_besondereflurstuecksgrenze(boolean) line 41 at RAISE|
> psql:postprocessing.d/1_ableitungsregeln/11002.sql:228: NOTICE:  adfs:{7107} sn:2024 n:0|
> CONTEXT:  PL/pgSQL function pg_temp_2.alkis_besondereflurstuecksgrenze(boolean) line 41 at RAISE|
> psql:postprocessing.d/1_ableitungsregeln/11002.sql:228: NOTICE:  adfs:{7003} sn:2014 n:26155|
> CONTEXT:  PL/pgSQL function pg_temp_2.alkis_besondereflurstuecksgrenze(boolean) line 41 at RAISE|
> psql:postprocessing.d/1_ableitungsregeln/11002.sql:228: NOTICE:  adfs:{3000} sn:2012 n:27563|
> CONTEXT:  PL/pgSQL function pg_temp_2.alkis_besondereflurstuecksgrenze(boolean) line 41 at RAISE|
>  Politische Grenze verschmolzen|
postprocessing.d\1_ableitungsregeln\11002.sql ausgeführt.
>  Grenzpunkte werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\11003.sql ausgeführt.
>  Lagebezeichnungen ohne Hausnummer werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\12001.sql ausgeführt.
>  Lagebezeichnungen mit Hausnummer werden verarbeitet.|
>   Ortsteil verarbeitet.|
>   Gebäudehausnummern werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\12002.sql ausgeführt.
>  Lagebezeichnungen mit Pseudonummer werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\12003.sql ausgeführt.
>  Gebäude werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\31001.sql ausgeführt.
>  Gebäudeteile werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\31002.sql ausgeführt.
>  Tatsächliche Nutzungen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\41001.sql ausgeführt.
>  Industrie- und Gewerbeflächen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\41002.sql ausgeführt.
>  Halden werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\41003.sql ausgeführt.
>  Bergbaubetriebe werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\41004.sql ausgeführt.
>  Tagebaue werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\41005.sql ausgeführt.
>  Flächen gemischter Nutzung werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\41006.sql ausgeführt.
>  Flächen besonderer funktionaler Prägung werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\41007.sql ausgeführt.
>  Sport-, Freizeit- und Erholungsflächen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\41008.sql ausgeführt.
>  Friedhöfe werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\41009.sql ausgeführt.
>  Wege werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\42006.sql ausgeführt.
>  Plätze werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\42009.sql ausgeführt.
>  Bahnverkehr wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\42010.sql ausgeführt.
>  Flugverkehr wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\42015.sql ausgeführt.
>  Schiffsverkehr wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\42016.sql ausgeführt.
>  Landwirtschaft wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\43001.sql ausgeführt.
>  Wald wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\43002.sql ausgeführt.
>  Gehölze werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\43003.sql ausgeführt.
>  Heide wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\43004.sql ausgeführt.
>  Moor wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\43005.sql ausgeführt.
>  Sumpf wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\43006.sql ausgeführt.
>  Unland/vegetationslose Flächen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\43007.sql ausgeführt.
>  Fließgewässer werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\44001.sql ausgeführt.
>  Hafenbecken werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\44005.sql ausgeführt.
>  Stehende Gewässer werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\44006.sql ausgeführt.
>  Meere werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\44007.sql ausgeführt.
>  Bauwerke oder Anlagen für Industrie und Gewerbe werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\51002.sql ausgeführt.
>  Vorratsbehälter, Speicherbauwerke werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\51003.sql ausgeführt.
>  Transportanlagen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\51004.sql ausgeführt.
>  Leitungen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\51005.sql ausgeführt.
>  Bauwerke oder Anlagen für Sport, Freizeit und Erholung werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\51006.sql ausgeführt.
>  Historische Bauwerke oder Einrichtungen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\51007.sql ausgeführt.
>  Heilquellen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\51008.sql ausgeführt.
>  Sonstige Bauwerke oder Einrichtungen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\51009.sql ausgeführt.
>  Einrichtungen in öffentlichen Bereichen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\51010.sql ausgeführt.
>  Bauwerke in Verkehrsbereich werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\53001.sql ausgeführt.
>  Straßenverkehrsanlagen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\53002.sql ausgeführt.
>  Wege, Pfade und Steige werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\53003.sql ausgeführt.
>  Bahnverkehrsanlagen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\53004.sql ausgeführt.
>  Seil- und Schwebebahnen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\53005.sql ausgeführt.
>  Flugverkehrsanlagen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\53007.sql ausgeführt.
>  Einrichtungen für den Schiffsverkehr werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\53008.sql ausgeführt.
>  Bauwerke im Gewässerbereich werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\53009.sql ausgeführt.
>  Vegetationsmerkmale werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\54001.sql ausgeführt.
>  Türme werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\55001.sql ausgeführt.
>  Untergeordnete Gewässer werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\55002.sql ausgeführt.
>  Gleise werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\55006.sql ausgeführt.
>  Wasserspiegelhöhen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\57001.sql ausgeführt.
>  Schifffahrtslinien werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\57002.sql ausgeführt.
>  Einrichtungen im öffentlichen Bereichen (NRW) werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\59102.sql ausgeführt.
>  Bauwerke und Anlagen für Ver- und Entsorgen (NRW) werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\59103.sql ausgeführt.
>  Sonstige Bauwerke (NRW) werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\59109.sql ausgeführt.
>  Einrichtung im Straßenverkehr (NRW) werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\59201.sql ausgeführt.
>  Verkehrszeichen (NRW) werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\59202.sql ausgeführt.
>  Einrichtungen im Bahnverkehr (NRW) werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\59206.sql ausgeführt.
>  Bauwerke im Gewässerbereich (NRW) werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\59207.sql ausgeführt.
>  Vegetationsmerkmale (NRW) werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\59301.sql ausgeführt.
>  Bau-, Raum- oder Bodenordnungsrecht (NRW) wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\59401.sql ausgeführt.
>  Kommunaler Besitz (NRW) wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\59402.sql ausgeführt.
>  Böschungen und Kliffe werden verarbeitet.|
>  Böschungen berechnet.|
> psql:postprocessing.d/1_ableitungsregeln/61001.sql:281: NOTICE:  0 Böschungen|
> CONTEXT:  PL/pgSQL function pg_temp_2.alkis_boeschung() line 253 at RAISE|
postprocessing.d\1_ableitungsregeln\61001.sql ausgeführt.
>  Dämme, Wälle und Deiche werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\61003.sql ausgeführt.
>  Höhleneingänge werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\61005.sql ausgeführt.
>  Felsen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\61006.sql ausgeführt.
>  Dünen werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\61007.sql ausgeführt.
>  Höhenlinien werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\61008.sql ausgeführt.
>  Besondere topographische Punkte werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\61009.sql ausgeführt.
>  Geländekanten werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\62040.sql ausgeführt.
>  Klassifizierungen nach Straßenrecht werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\71001.sql ausgeführt.
>  Klassifizierungen nach Wasserrecht werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\71003.sql ausgeführt.
>  Klassifizierungen nach Natur-, Umwelt und Bodenschutzrecht werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\71006.sql ausgeführt.
>  Schutzgebiete nach Natur-, Umwelt und Bodenschutzrecht werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\71007.sql ausgeführt.
>  Bauraum und Bauordnungsrecht wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\71008.sql ausgeführt.
>  Denkmalschutzrecht wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\71009.sql ausgeführt.
>  Sonstiges Recht wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\71011.sql ausgeführt.
>  Landwirtschaftliche Nutzung (RP) wird verarbeitet.|
postprocessing.d\1_ableitungsregeln\72004.sql ausgeführt.
>  Wohnplätze werden verarbeitet.|
postprocessing.d\1_ableitungsregeln\74005.sql ausgeführt.
>  Migrationsobjekte werden verarbeitet.|
>  Migrationsobjekte ohne Signatur | Anzahl|
> ---------------------------------+--------|
>                             1047 |     26|
>                             1045 |      8|
>                             1043 |      3|
>                             1041 |      4|
postprocessing.d\1_ableitungsregeln\91001.sql ausgeführt.
>  Nachbearbeitung läuft...|
>  ALKIS-Modellart | #Objekte|
> -----------------+----------|
>  DLKM            |   875137|
>  DKKM1000        |   277933|
>  DKKM2000        |   200602|
>    ALKIS-Modellart   | #Objekte|
> ---------------------+----------|
>  {DLKM}              |   875137|
>  {DKKM1000}          |   277596|
>  {DKKM2000}          |   200265|
>  {DKKM1000,DKKM2000} |      337|
>  Lösche nicht darzustellende Signaturen...|
>  Fehlende Signaturen | Anzahl | Signaturen|
> ---------------------+--------+------------|
>  Beschriftungen      |      9 | {4133}|
>  Linien              |    813 | {4115}|
postprocessing.d\2_ableitungsregeln.sql ausgeführt.
postprocessing.d\3_nas2alb.sql ausgeführt.
>  Prüfe Flurstücksgeometrien...|
>  Übertrage Flurstücke...|
>  Belege Baulastenblattnummer...|
postprocessing.d\4_nas2alb\1_flurst.sql ausgeführt.
>  Erzeuge Straßenzuordnungen...|
postprocessing.d\4_nas2alb\2_strassen.sql ausgeführt.
"> psql:postprocessing.d/4_nas2alb/3_eignerart.sql:42: ERROR:  duplicate key value violates unique constraint ""eignerart_pkey""|"
> DETAIL:  Key (flsnr, bestdnr, bvnr)=(082155-000-00044/001 , 082155-0000042  , 0004) already exists.|
Fehler bei Prozeß: 3
postprocessing.d\4_nas2alb\3_eignerart.sql gescheitert.
Import nach 1h51m17s abgebrochen.

**Comment by tonyhawk127** [comment]
Ich schließe mich an dieser Stelle mal an. Beim Import der ALKIS-Daten der Stadt Leipzig (Sachsen), erhalte ich die identische Fehlermeldung bei der Eignerart, 
[alkis_import_leipzig.log](https://github.com/norBIT/alkisimport/files/4214066/alkis_import_leipzig.log)
also kurz:

2020-02-17T14:14:33 postprocessing.d\4_nas2alb\3_eignerart.sql gescheitert.
2020-02-17T14:14:33 Import nach 1h46m46s abgebrochen.

Gibt es hier schon eine Lösung? Die Daten können über folgenden Direktlink bezogen werden:
https://geocloud.landesvermessung.sachsen.de/index.php/s/6xo9Molxr4x7hQy/download?path=%2F&files=14713000.xml.zip
