### ISSUE TITLE
fehlende Flurstücksdaten bei Import von NAS-Daten ohne Eigentümer

### ISSUE THREAD

**Issue by guenterw** [norBIT/alkisimport#34]
Beim Import von ALKIS-NAS-Daten ohne Eigentümerdaten fehlt die gesamte Flurstücksinformation incl. Flurstücksgrenzen.
Getestet mit 3.0-10 und 3.0-11, Windows 10 64bit, OSGeo4W - Installation.

**Comment by jef-n** [comment]
Gibt's Testdaten?

**Comment by jef-n** [comment]
Fixed in b36f7bc2538
