### ISSUE TITLE
Fehlerhafter Import über Linux-Shellskript in leere Datenbank

### ISSUE THREAD

**Issue by henneyng** [norBIT/alkisimport#36]
Hallo,

gerne würde ich von https://www.opengeodata.nrw.de/produkte/geobasis/lika/alkis_sek/bda_oe/ heruntergeladene ALKIS-Daten mit dem Linux-Skript in eine frische Postgis-Datenbank importieren. Unter Debian 10 habe ich eine Datenbank mit Namen "alkis" angelegt und in pgadmin3 den Befehl "CREATE EXTENSION postgis" auf die Datenbank ausgeführt.

Eine Steuerdatei habe ich entsprechend http://www.norbit.de/68/ angelegt (die letzte Zeile jeweils für alle xml-Dateien):
PG:host=xpostgis dbname=alkis user=postgres password=******
create log debug
/xdata/xpostgis/alkis-nas/bda_oe_..._EPSG25832_NAS/fachinformationen_..._bda.xml.gz -skipfailures

Beim Import über das Skript mit der Steuerdatei kommt direkt ein Fehler:
henning@xpostgis:~$ /xdata/xpostgis/alkisimport-master/alkis-import.sh /xdata/xpostgis/alkis-nas/nas-import.lst
START 2019-08-06 17:21:57
GDAL 2.4.0, released 2018/12/14
SQL RUN: preprocessing.d/0_alkis-signaturen.sql 2019-08-06 17:21:57
      ?column?
--------------------
 Lade Signaturen...
(1 Zeile)

psql:preprocessing.d/0_alkis-signaturen.sql:25: FEHLER:  Relation »alkis_flaechen« existiert nicht
ZEILE 1: DELETE FROM alkis_flaechen;
                     ^
psql:preprocessing.d/0_alkis-signaturen.sql:25: ANWEISUNG:  DELETE FROM alkis_flaechen;
SQL DONE[3]: preprocessing.d/0_alkis-signaturen.sql 2019-08-06 17:21:57 in 0,nichts
FEHLER BEIM PREPROCESSING
END 2019-08-06 17:21:57
henning@xpostgis:~$ 

Über das Windows-GUI kommt dieser Fehler nicht und ich könnte in die Datenbank importieren. Ich vermute, dass über das Windows-GUI vorher noch ein Schema angelegt wird und das löschen aus den dann bereits angelegten Tabellen somit klappt. Wenn ich das Skript richtig lese (Zeile 672 ff.) sollte das Schema eigentlich durch das "create" in der Steuerdatei angelegt werden.

Hat jemand eine Idee, wo sich Bug oder Bedienfehler versteckt?

Vieelen Dank & beste Grüße
Henning

**Comment by jef-n** [comment]
`create` und `log` muß auf getrennten Zeilen stehen, ebenso `options -skipfailures`

**Comment by henneyng** [comment]
Hallo,

vielen Dank, der Hinweis löst das Problem.

Auf Debian 10 mit Python3 musste ich in der Datei refilter.py allerdings noch Zeile 22: 
`from builtins import str`
ersetzen durch (Anwendung des Hinweises von https://askubuntu.com/questions/697226/importerror-no-module-named-builtins):
`try:`
`    from builtins import str`
`except ImportError:`
`    from __builtin__ import str`

Beste Grüße
Henning

**Comment by jef-n** [comment]
> Über das Windows-GUI kommt dieser Fehler nicht

Die GUI ist übrigens nicht auf Windows beschränkt.
