### ISSUE TITLE
Fehler beim Postprocessing - bei ALKIS Daten mit Punktinformationen (Sachsen)

### ISSUE THREAD

**Issue by j-lippmann** [norBIT/alkisimport#37]
Beim Import der ALKIS Daten von Sachsen - konkret von Chemnitz - wird er Import abgebrochen. Details siehe log. liegt es an den Daten? Oder am ALKIS-Import? 

https://www.geodaten.sachsen.de/downloadbereich-alkis-4176.html 
(dort ALKIS Download mit Punktinformationen (gemeindeweise) auswählen und dann Stadt Chemnitz)
[alkis-import-fehler.log](https://github.com/norBIT/alkisimport/files/4126783/alkis-import-fehler.log)

**Comment by j-lippmann** [comment]
Mit einer kleineren Dorfgemeinde läuft alles ohne Fehler durch. @jef-n kann ich noch etwas beitragen in form von testen etc.?

**Comment by jef-n** [comment]
Duplicate of #27

**Comment by tonyhawk127** [comment]
Ich schließe mich an dieser Stelle mal an. Beim Import der ALKIS-Daten der Stadt Leipzig (Sachsen), erhalte ich die identische Fehlermeldung bei der Eignerart, also kurz:

_2020-02-17T14:14:33 postprocessing.d\4_nas2alb\3_eignerart.sql gescheitert.
2020-02-17T14:14:33 Import nach 1h46m46s abgebrochen._

Gibt es hier schon eine Lösung? Die Daten können über folgenden Direktlink bezogen werden:
https://geocloud.landesvermessung.sachsen.de/index.php/s/6xo9Molxr4x7hQy/download?path=%2F&files=14713000.xml.zip
