### ISSUE TITLE
Berücksichtigung der Ausrichtung von Flurstücksnummern

### ISSUE THREAD

**Issue by olis84** [norBIT/alkisimport#39]
Bei den Flustücksnummern wird für die horizontale Ausrichtung der Bruchstrich fix auf "zentrisch" gesetzt. Allerdings werden so nicht die rechts- oder linksbündigen Ausrichtungen berücksichtigt. 
Im Fall der Bruchstriche ließ sich dies durch Verschiebung deren End- und Anfangspunkte erreichen. Für die Darstellung der Zähler und Nenner reicht es nicht, dass man einfach die Ausrichtung durchreicht und vom MapServer entsprechend die Labels positionieren lässt. Dann werden rechts- oder linksbündige Flurstücksnummern nicht konform zum ALKIS-SK dargestellt, da die jeweils kleine Zahl nicht mittig auf dem Bruchstrich steht. Hierzu musste also der Punkt in die Mitte des Brcuhstriches verschoben werden, sodass der MapServer immer nur zentrisch darstellen muss.
Anbei die erweiterte SQL.
[11001.sql.zip](https://github.com/norBIT/alkisimport/files/4643570/11001.sql.zip)

**Comment by jschrae** [comment]
Hallo,

so richtig passt die Positionierung der Flurstücksnummern mit der Anpassung von olis84 jedoch nicht.
siehe dazu:
https://github.com/norBIT/alkisimport/issues/40#issue-652193632

Gruß
Jens
