### ISSUE TITLE
verschobene Darstellung von Zähler und Nenner

### ISSUE THREAD

**Issue by dgrohmann** [norBIT/alkisimport#40]
Hallo,

nach einem erfolgreich durchgeführten ALKIS-Import stellen sich die Flurstücksbezeichnungen (Zähler, Nenner) relativ verschoben zum Bruchstrich dar (s. Screenshot).  Ich nutze die QGIS-Erweiterung "norGIS ALKIS-Einbindung" V 2.0.43, der Import wurde mit "norGIS ALKIS-Import" V 3.0-29 durchgeführt.

Woran kann die verschobene Darstellung von Zähler und Nenner liegen?

![QGIS_norbit_flstkbezeichnung](https://user-images.githubusercontent.com/67319293/86766187-76b66800-c04a-11ea-974b-d418e2c589c5.jpg)

Danke und Gruß
Daniel Grohmann

**Comment by jschrae** [comment]
Hallo,
bei mir ist bzw. war die Darstellung der Flurstücksnummern genau so. Die Änderungen von Oliver Schmidt vom Mai sind wohl nicht so ganz gelungen. 
Ich habe das Script geändert 11001.sql ein wenig angepasst und nun kommt die Positionierung der Flurstücksnummern dem ALKIS-Signaturenkatalog ziemlich nahe. 
Vielleicht probierst du es mal mit dem von mir geändertem SQL-Script.

[11001_mod.sql.txt](https://github.com/norBIT/alkisimport/files/4986014/11001_mod.sql.txt)

Gruß
Jens

**Comment by dgrohmann** [comment]
Hallo Jens,
bin aus dem Urlaub zurück und teste gleich mal dein Skript ...

Vielen Dank schonmal im Voraus.

BG
Daniel

**Comment by dgrohmann** [comment]
Hallo Jens,
dein modifiziertes Skript bringt den gewünschten Effekt. Die Flurstücksbezeichnung (Zähler, Nenner) sitzt nun optisch wieder "richtig" auf dem Bruchstrich ;-)

Sieht nun so wie bei dir aus ...
![ALKIS-Import_verschobeneFlurstuecksbezeichnung_geloest](https://user-images.githubusercontent.com/67319293/90477651-0fe99b80-e12c-11ea-81c8-67a0c88ca665.jpg)

Vielen Dank für deine Hilfe!

BG Daniel

**Comment by jschrae** [comment]
Super, es freut mich, dass das auch bei dir funktioniert.
Gruß Jens
