### ISSUE TITLE
Alkis- Import startet nicht

### ISSUE THREAD

**Issue by schorsch2** [norBIT/alkisimport#41]
Ich versuche Alkis-Import unter Windows zu starten. Zur Installation habe ich osgeo4win- Installer verwendet. Es existiert ein Verzeichnis c:\OSGeo4W\apps\alkis-import\.
Nach Start über das Icon ist weder ein Fenster noch eine Fehlermeldung zu sehen.

**Comment by jef-n** [comment]
Zum Debuggen:  In `c:\osgeo4w\bin\alkis-import.cmd` in der letzten Zeile `pythonw` gegen `python` austauschen und dann `alkis-import.cmd` aus der OSGeo4W Shell starten - dort sollten dann ggf. Fehlermeldungen zu sehen sein.

**Comment by schorsch2** [comment]
So funktioniert das Programm - auch ohne Fehlermeldungen. Ich bin mir sicher, es funktionierte gestern nicht.
Über das Icon klappt es auch heute noch nicht. Aber vielleicht probiere ich es am Montag noch mal ;-)

**Comment by schorsch2** [comment]
Funktioniert!
