### ISSUE TITLE
Import unter Windows automatisieren

### ISSUE THREAD

**Issue by ewie** [norBIT/alkisimport#50]
Ist es möglich den Import unter Windows zu automatisieren, also die UI von `alkisImport.py` zu umgehen?

Ich habe es bereits mit `alkis-import.sh` über Cygwin probiert, was auch weitestgehend läuft, wenn ich [`postgresql-client`](https://cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Fpostgresql-client%2Fpostgresql-client-14.2-1&grep=psql) und [`gdal`](https://cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Fgdal%2Fgdal-3.4.1-1&grep=ogr2ogr) installiere.

Letztendlich gibt es aber ein Problem mit `parallel`, das ich über Package [`moreutils`](https://cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Fmoreutils%2Fmoreutils-0.67-1&grep=parallel) installiert habe. Der Fehler ist:
```
SQL DONE[0]: postprocessing.d/0_ableitungsregeln.sql 2022-04-22 22:02:58 in 1s
parallel: unknown option -- -
parallel [OPTIONS] command -- arguments
        for each argument, run command with argument, in parallel
parallel [OPTIONS] -- commands
        run specified commands in parallel
FEHLER BEIM POSTPROCESSING
END 2022-04-22 22:02:59
```
Meine Kenntnisse in Sachen Cygwin und Windows halten sich aber in Grenzen.

Mein Ziel ist es den Import unter Linux als auch Windows (andere Teammitglieder nutzen Windows) zu automatisieren. Vielleicht lässt sich `alkisImport.py` dahingehend anpassen, um den Import analog zu `alkis-import.sh` über eine Datei zu konfigurieren. Beim Überfliegen des Python-Scripts ist mir keine derartige Funktion aufgefallen, die eventuell nur undokumentiert ist.

**Comment by jef-n** [comment]
> Ist es möglich den Import unter Windows zu automatisieren, also die UI von `alkisImport.py` zu umgehen?

Ja, `alkis-import.sh` braucht allerdings [GNU parallel](https://www.gnu.org/software/parallel/) (perl-Skript) und nicht moreutils' parallel.

Siehe auch [minimal installation im README](http://git.savannah.gnu.org/cgit/parallel.git/plain/README):

```
= Minimal installation =

If you just need parallel and do not have 'make' installed (maybe the
system is old or Microsoft Windows):

    wget https://git.savannah.gnu.org/cgit/parallel.git/plain/src/parallel
    chmod 755 parallel
    cp parallel sem
    mv parallel sem dir-in-your-$PATH/bin/
```
