### ISSUE TITLE
Funktionsnamen in alkis-compat

### ISSUE THREAD

**Issue by lvgl-pl** [norBIT/alkisimport#51]
wie in #49 vorgeschlagen, habe ich die aktuelle Version des Alkis - Importers für einen Erstimport verwendet.

In der Logdatei sind einige Fehler aufgetreten, z.B.

(1) psql:alkis-compat.sql:195: FEHLER:  Funktion »st_makevalid« existiert bereits mit den selben Argumenttypen

(2) psql:alkis-compat.sql:378: FEHLER:  Funktion st_force_2d(geometry) existiert nicht
ZEILE 2:   SELECT st_force_2d($1);
                  ^
TIP:  Keine Funktion stimmt mit dem angegebenen Namen und den Argumenttypen überein. Sie müssen möglicherweise ausdrückliche Typumwandlungen hinzufügen.

-----------------------------------------------

Es geht mehr um Fehlermeldungen vom Typ (2). Hat dies negativen Einfluss auf die Importe?

Es gab in einem Forum ein ähnliches Problem:

https://lists.fossgis.de/pipermail/fossgis-talk-liste/2020-January/010411.html

Wir haben die Postgis Version 3.2. Beim Recherchieren ergab sich, wie in dem Forumsbeitrag auch, dass z.B. 
Funktionen seit Postgis Version 2.1 ohne Unterstrich geschrieben werden.

**Comment by jef-n** [comment]
Fehlermeldung in alkis-compat.sql sind normal.  Das erzeugt mit alten PostGIS-Versionen neue Funktionen mit den aktuellen Schnittstellen, sodass in den Skripten die aktuelle Schnittstelle genutzt werden kann auch, wenn eine ältere PostGIS-Version vorliegt - das klappt aber nur, wenn die aktuellen Schnittstelle nicht bereits vorliegt.

Das Problem waren in https://lists.fossgis.de/pipermail/fossgis-talk-liste/2020-January/010411.html die OIDS.
