### ISSUE TITLE
Fehler beim Postprocessing

### ISSUE THREAD

**Issue by schorsch2** [norBIT/alkisimport#52]
Während des Imports erhalte ich folgende Fehlermeldung:
`  Erzeuge Flurstücksnummern in Schrägstrichdarstellung...
 SQL DONE[2]: postprocessing.d/1_ableitungsregeln/11001.sql 2022-07-19 07:58:23 in 3s
 psql:postprocessing.d/1_ableitungsregeln/11001.sql:70: FATAL:  failed to load summary "/usr/lib/postgresql13/lib64/bitcode/postgis-3.index.bc": Invalid summary version 7, 1, 2, 3 or 4 expected
 Server beendete die Verbindung unerwartet
        Das heißt wahrscheinlich, dass der Server abnormal beendete
        bevor oder während die Anweisung bearbeitet wurde.
 psql:postprocessing.d/1_ableitungsregeln/11001.sql:70: Fatal: Verbindung zum Server wurde verloren
 parallel: This job failed:
 sql postprocessing.d/1_ableitungsregeln/11001.sql
 parallel: Starting no more jobs. Waiting for 0 jobs to finish.
 FEHLER BEIM POSTPROCESSING
 END 2022-07-19 07:58:23
`
Ich verwende Postgres auf OpenSuse Leap 15.3
Gibt es eine Möglichkeit den Import trotzdem durchzuführen?

**Comment by jef-n** [comment]
Das sieht eher nach einem lokalen PostGIS-Installationsproblem denn nach einem Problem des ALKIS-Import aus (ich finde eine ähnlich Fehlermeldung nur in https://gis.stackexchange.com/questions/377833/postgis-wont-update-geometry-when-importing-csv-file-with-psql)
