### ISSUE TITLE
alkis_farben definiert Unique Constraint auf nullable Spalten

### ISSUE THREAD

**Issue by ewie** [norBIT/alkisimport#55]
Mir ist aufgefallen, dass `alkis_farben` mit `UNIQUE(c, y, m, k)` definiert ist, obwohl die vier Spalten nullable sind. Ich denke mal, dass die CMYK- und auch RGB-Werte generell nicht nullable sein sollten (unabhängig vom Unique Constraint).

Die Query, mit der ich meine Datenbanken nach solchen Fällen durchsucht habe:

```pgsql
select
  k.conrelid::regclass,
  k.conname,
  array_agg(a.attname order by a.attnum) as attnames
from
  pg_constraint k
  cross join
    unnest(k.conkey) keyattnum
  join
    pg_attribute a
      on a.attrelid = k.conrelid
      and a.attnum = keyattnum
      and not a.attnotnull
where
  k.contype = 'u'
group by
  1, 2
```

**Comment by jef-n** [comment]
alkis_farben hat statischen Inhalt.

**Comment by ewie** [comment]
Danke. Ich hätte gedacht, es lassen sich Farben nachträglich eintragen.
