### ISSUE TITLE
Buchungsart Aufgeteiltes Erbbaurecht WEG (2201) gibt keine Eigentümer aus

### ISSUE THREAD

**Issue by marvinkinberger** [norBIT/alkisimport#58]
In dem Fall, dass auf einem Flurstück ein fitkives Grundbuchblatt (5000) mit einer Buchungsstelle der Buchungsart 2201 (Aufgeteiltes Erbbaurecht WEG) gebucht ist, werden keine Eigentümer in der Auskunft angezeigt. 
Hier muss eine weitere Buchungsstelle über die Relation "an" gesucht werden um die Informationen für die Erbbauberechtigten zu finden.

**Comment by jef-n** [comment]
implemented in aa9b25b7b684 ff.
