### ISSUE TITLE
Auswirkungen der Umstellung von GeoInfoDok 6.0 auf GeoInfoDok 7.1

### ISSUE THREAD

**Issue by danceb** [norBIT/alkisimport#60]
Hallo,

das Land Thüringen stellt zum 01.01.2024 bei der Datenlieferung von NAS-Daten auf eine neue Version des AAA-Datenmodells von GeoInfoDok 6.0 auf GeoInfoDok 7.1 um. Wir importieren unsere NAS-Daten, die wir halbjährlich vom Land bekommen, per alkisimport in unsere PostGIS-Datenbank.

Mir ist zu diesem Punkt noch nicht ganz klar, ob und welche Auswirkung diese Umstellung haben wird. Wird die neuere Version GeoInfoDok 7.1 vom alkispimport unterstützt und können die Daten entsprechend fehlerfrei importiert werden? In der FOSSGIS-Liste kam die Rückmeldung (https://lists.fossgis.de/pipermail/fossgis-talk-liste/2023-May/012525.html), dass es in Hessen, wo bereits auf die neue Version umgestellt worden ist, wohl zu einer Fehlermeldung beim Import kam (welche ist leider nicht mehr bekannt). 
Gibt es auch von anderer Seite aus bereits die Anforderung, dass der Import auch mit GeoInfoDok 7.1 funktioniert und müsste man die Anwendung entsprechend anpassen/erweitern?

Vielen Dank für eine Rückmeldungen hierzu!

**Comment by Meinolf-geoGLIS** [comment]
Hallo,
auch das Land Schleswig-Holstein stellt Ende 2023 auf GeoInfoDok 7.1.2 um. 
Daher auch von uns die Frage ob entsprechende Anpassungen am alkisimport geplant sind.
Infos und Testdaten aus SH sind [hier ](https://www.schleswig-holstein.de/DE/landesregierung/ministerien-behoerden/LVERMGEOSH/Themen/themaGeoinfoDok/themaGeoinfodok7.html?nn=b7e3eb10-4e7a-4dd0-8caf-a8911c06430a) herunterladbar.
Ein einfache Übersicht der Änderungen gegenüber GeoInfoDok 6 aus bayrischer Sicht ist [hier ](https://www.ldbv.bayern.de/file/pdf/16143/ALKIS-OK-BY_%C3%84nderungen_V_2_0.pdf ) zu finden.

Über eine Rückmeldung würde ich mich freuen.

**Comment by jef-n** [comment]
Der [GID7-Branch](https://github.com/norBIT/alkisimport/tree/gid7) unterstützt das neuen Datenmodell bereits. In OSGeo4W gibt es auch ein entsprechendes Paket (alkis-import-gid7).   Die neuen Signaturenkataloge sind allerdings noch nicht umgesetzt - daran wird noch gearbeitet.   Derzeit werden noch die alten verwendet.
