### ISSUE TITLE
Tabelle aa_weiteremodellart ist nicht gefüllt und Information zu sonstigesmodell  wurde nicht importiert

### ISSUE THREAD

**Issue by astroidex** [norBIT/alkisimport#65]
Die Tabelle aa_weiteremodellart wird über das SQL alkis-schema.sql erstellt. Sie ist allerdings nicht gefüllt. Die Tabelle ist vom UML-Typ: Code Liste. Werden hier nicht Einträge erwartet?

Mit der Version gid7 werden Information zu sonstigesmodell z.B. in der Tabelle ap_pto nicht mehr gefüllt. Beim Import via GID6 liegen Angaben in der Spalte sonstigesmodell vor.

GID6 Import
![sonstigesmodell_gid6_spalte](https://github.com/norBIT/alkisimport/assets/996298/6c051dfc-3598-4981-83d7-555ce4405597)

GID7 Import
![sonstigesmodell_gid7_spalte](https://github.com/norBIT/alkisimport/assets/996298/db07499d-dcef-4dbf-b1bc-abfbe942aff8)

![nas](https://github.com/norBIT/alkisimport/assets/996298/8313d932-c1c9-4d12-84a6-09789e88442f)

**Comment by jef-n** [comment]
Zu `aa_weiteremodellart` legt das GID7-Schema keinen Inhalt fest.

ME sollte das Modell als Text und nicht als title-Attribut da stehen.  Also `<sonstigesModell>NWAKBK5</sonstigesModell>`  - analog zu  `<advStandardModell>DLKM</advStandardModell>`

**Comment by astroidex** [comment]
Das macht Sin. Also ist es eher ein Fall für die NAS-Dateierstellung.

**Comment by astroidex** [comment]
Werde ich so weitergeben und Rückmeldung geben.

**Comment by jef-n** [comment]
Das betrifft nicht nur das `sonstigeModell`, was es anscheinend nur in NRW verwendet wird - zumindest habe ich es in keinen Testdaten gefunden. `anlass`  ist ein besseres Beispiel findet sich aber überall findet (und oben).

```xml
                                <AX_Flurstueck gml:id="DEHER7LK10005DrL">
                                        <gml:identifier codeSpace="http://www.adv-online.de/">urn:adv:oid:DEHER7LK10005DrL</gml:identifier>
…
                                        <anlass xlink:title="Ersteinrichtung" xlink:href="https://registry.gdi-de.org/codelist/de.adv-online.gid/AA_Anlassart/000000"/>
```
