### ISSUE TITLE
Fehlerhafter Import via alkis-import.sh je nach Reihenfolge der Parameter

### ISSUE THREAD

**Issue by astroidex** [norBIT/alkisimport#66]
Werden gid7-Daten mit alkis-import.sh in ein Schema importiert, scheint die Reihenfolge der Parameter relevant zu sein. Dies ist unpraktisch. 

Scheinbar müssen schema und pgschema vor create angegeben werden, da sonst viele Tabelle nicht im schema (siehe Bsp alkis) landen sondern unter public.

1. Fall mit Fehler: nur 6 Tabellen im ALKIS-Schema Variable schema  (in dem Bsp: alkis) und der Rest landet unter public

```
PG:host=localhost port=5432 dbname=demo user=user password=user
create 
epsg 25832
pgschema public
schema alkis
log true 
```

2. Fall ohne Fehler:  667 Tabellen werden korrekt im ALKIS-Schema Variable schema (in dem Bsp: alkis) angelegt

```
PG:host=localhost port=5432 dbname=demo user=user password=user
epsg 25832
pgschema public
schema alkis
create
log true 
```

**Comment by jef-n** [comment]
Die Optionen werden sequentiell verarbeitet.  Schema und Koordinatensystem muß daher vor "create" angegeben werden.

**Comment by astroidex** [comment]
Die Information könnte in der Dokumentation angegeben werden. https://www.norbit.de/68/
