### ISSUE TITLE
ADV 7.1.2 / ax_klassifizierung_bewertung

### ISSUE THREAD

**Issue by FroehDo** [norBIT/alkisimport#74]
Der Table ax_klassifizierung_bewertung in alkis-update.sql 8069ff muss für Konformität mit ADV 7.1.2 folgendermaßen aussehen:

		CREATE TABLE ax_klassifizierung_bewertung (
		  wert integer,
		  beschreibung character varying,
		  dokumentation character varying,
		  PRIMARY KEY (wert)
		);

		COMMENT ON TABLE ax_klassifizierung_bewertung IS 'Alias: "AX_Klassifizierung_Bewertung", UML-Typ: Enumeration';
		INSERT INTO ax_klassifizierung_bewertung (wert,beschreibung,dokumentation) VALUES
		('1000', 'Grundvermögen', ''),
		('1110', 'Unbebautes Grundstück', ''),
		('1120', 'Unbebautes Grundstück mit Gebäude von untergeordneter Bedeutung', ''),
		('1130', 'Unbebautes Grundstück mit einem dem Verfall preisgegebenen Gebäude', ''),
		('1140', 'Unbebautes Grundstück für Erholungs- und Freizeitzwecke', ''),
		('1210', 'Einfamilienhausgrundstück', ''),
		('1220', 'Zweifamilienhausgrundstück', ''),
		('1230', 'Mietwohngrundstück', ''),
		('1240', 'Gemischtgenutztes Grundstück', ''),
		('1250', 'Geschäftsgrundstück', ''),
		('1260', 'Sonstiges bebautes Grundstück', ''),
		('1310', 'Einfamilienhaus auf fremdem Grund und Boden', ''),
		('1320', 'Zweifamilienhaus auf fremdem Grund und Boden', ''),
		('1330', 'Mietwohngrundstück, Mietwohngebäude auf fremdem Grund und Boden', ''),
		('1340', 'Gemischtgenutztes Grundstück, gemischtgenutztes Gebäude auf fremdem Grund und Boden', ''),
		('1350', 'Geschäftsgrundstück, Geschäftsgebäude auf fremdem Grund und Boden', ''),
		('1360', 'Sonstige bebaute Grundstücke, sonstige Gebäude auf fremdem Grund und Boden', ''),
		('1370', 'Sonstige bebaute Grundstücke, sonstige Anlagen auf fremdem Grund und Boden (Energie-/Wärmegewinnung)', ''),
		('3000', 'Landwirtschaftliche Nutzung (LN)', ''),
		('3100', 'Forstwirtschaftliche Nutzung (H)', ''),
		('3105', 'Forstwirtschaftliche Nutzung mit Bewirtschaftungsbeschränkung (HB)', ''),
		('3200', 'Weinbauliche Nutzung (WG)', ''),
		('3201', 'Weingarten 1 (WG1)', ''),
		('3202', 'Weingarten 2 (WG2)', ''),
		('3203', 'Weingarten 3 (WG3)', ''),
		('3204', 'Weingarten 4 (WG4)', ''),
		('3205', 'Weingarten 5 (WG5)', ''),
		('3206', 'Weingarten 6 (WG6)', ''),
		('3207', 'Weingarten 7 (WG7)', ''),
		('3208', 'Weingarten 8 (WG8)', ''),
		('3209', 'Weingarten 9 (WG9)', ''),
		('3300', 'Gärtnerische Nutzung', ''),
		('3310', 'Gemüsebau - Freiland (GE)', ''),
		('3315', 'Gemüsebau - unter Glas und Kunststoffen (GEGL)', ''),
		('3320', 'Blumen- und Zierpflanzenbau - Freiland (BL)', ''),
		('3325', 'Blumen- und Zierpflanzenbau - unter Glas und Kunststoffen (BLGL)', ''),
		('3330', 'Obstbau - Freiland (OB)', ''),
		('3335', 'Obstbau - unter Glas und Kunststoffen (OBGL)', ''),
		('3340', 'Baumschulen - Freiland (BS)', ''),
		('3345', 'Baumschulen - unter Glas und Kunststoffen (BSGL)', ''),
		('3400', 'Übrige land- und forstwirtschaftliche Nutzungen', ''),
		('3410', 'Kleingarten- und Dauergartenland (KLG)', ''),
		('3411', 'Gartenlaube größer 30 qm (GL)', ''),
		('3420', 'Hopfen (HOPF)', ''),
		('3430', 'Spargel (SPA)', ''),
		('3440', 'Sonstige Sonderkulturen (SOKU)', ''),
		('3450', 'Saatzucht (SAAT)', ''),
		('3460', 'Weihnachtsbaumkultur (WEIH)', ''),
		('3470', 'Kurzumtriebsplantage (KUP)', ''),
		('3480', 'Wasserflächen (WAS)', ''),
		('3481', 'Wasserflächen - stehende Gewässer mit Fischertrag zwischen 1 und 4 kg/Ar (WAS1)', ''),
		('3482', 'Wasserflächen - stehende Gewässer mit Fischertrag über 4 kg/Ar (WAS4)', ''),
		('3490', 'Wasserflächen - fließende Gewässer mit Fischertrag (FLI)', ''),
		('3500', 'Nutzungsarten Abbauland, Geringstland und Unland ()', ''),
		('3510', 'Abbauland (AB)', ''),
		('3520', 'Geringstland (GER)', ''),
		('3530', 'Unland (U)', ''),
		('3600', 'Nutzungsart Hofstelle (NF)', ''),
		('3610', 'Hofstelle - Wirtschaftsgebäude im bewertungsrechtlichen Sinn (WIGE)', ''),
		('3611', 'Hofstelle - Wirtschaftsgebäude der Fass- und Flaschenweinerzeugung (WEIN)', ''),
		('3612', 'Hofstelle - Wirtschaftsgebäude der Imkerei (IMK)', ''),
		('3613', 'Hofstelle - Wirtschaftsgebäude der Wanderschäferei (SCHA)', ''),
		('3614', 'Hofstelle - Wirtschaftsgebäude des Pilzanbaus (PILZ)', ''),
		('3615', 'Hofstelle - Wirtschaftsgebäude der Produktion von Nützlingen (NÜTZ)', ''),
		('3616', 'Hofstelle - Wirtschaftsgebäude sonstiger Nebenbetriebe (NEB)', ''),
		('3700', 'weitere Nutzungen', ''),
		('3710', 'Windenergie (WEA)', ''),
		('3999', 'Nicht klassifiziert (NA)', '');

Nach: https://www.adv-online.de/GeoInfoDok/Aktuelle-Anwendungsschemata/AAA-Anwendungsschema-7.1.2-Referenz-7.1/binarywriterservlet?imgUid=87f70989-a7b6-0581-9393-b216067bef8a&uBasVariant=11111111-1111-1111-1111-111111111111#_C11309

Gruß
Dominik Fröhlich

**Comment by jef-n** [comment]
master ist für GID6,  gid7(i) ist für GID7.1.2.

**Comment by FroehDo** [comment]
Ah, alles klar. Danke!
