### ISSUE TITLE
ERROR:  null value in column "kulturart" violates not-null constraint

### ISSUE THREAD

**Issue by msochan** [norBIT/alkisimport#79]
Hey, I have encountered error "ERROR:  null value in column "kulturart" violates not-null constraint", while importing [ALKIS test data from Baden-Württemberg](https://www.lgl-bw.de/Produkte/Testdaten/Testdaten-Liegenschaftskataster/). 

Logs here [batch1_import_log_file.log](https://github.com/norBIT/alkisimport/files/15428529/batch1_import_log_file.log)

Do you have an idea how to fix this problem?

**Comment by jef-n** [comment]
You are probably trying to import data in the GeoInfoDok 7 format using master.  Use the gid7 or gid7i branch. master is still for GeoInfoDok 6.

**Comment by msochan** [comment]
Ah yea, sorry you are right, I will use another branch. Thank you! 🙏
