### ISSUE TITLE
Wird Reihenfolge der zu importierenden Dateien beachtet?

### ISSUE THREAD

**Issue by mrclBIE** [norBIT/alkisimport#80]
Bei dem ALKIS NAS Import ist es m.E. wichtig, dass die Reihenfolge der zu importierenden Dateien beachtet wird. Was passiert, wenn ich bspw. tägliche NBA Daten habe und mein täglicher, automatisierte Import ins Stocken geraten ist. Kann ich in der lst Steuerdatei einfach NAS Dateien mehrerer Tage angeben? Werden die Daten so importiert wie ich die Reihenfolge der zu importierenden Dateien in der lst Steuerdatei angebe?

**Comment by jef-n** [comment]
> Kann ich in der lst Steuerdatei einfach NAS Dateien mehrerer Tage angeben?

Ja.

> Werden die Daten so importiert wie ich die Reihenfolge der zu importierenden Dateien in der lst Steuerdatei angebe?

Das kommt darauf wie "jobs" eingestellt ist.   Die Daten der Liste werden bei >1 parallel eingespielt.  Die Reihe kann man dann aber auch mit etwas anderem als einer Datei, Leerzeile oder Kommentar teilen.  Dann werden die Teile nacheinander importiert, aber die Dateien darin parallel.

**Comment by mrclBIE** [comment]
Erstmal vielen Dank für die schnelle Rückmeldung!!! :)

> > Kann ich in der lst Steuerdatei einfach NAS Dateien mehrerer Tage angeben?
> 
> Ja.

Okay, sehr gut.

> > Werden die Daten so importiert wie ich die Reihenfolge der zu importierenden Dateien in der lst Steuerdatei angebe?
> 
> Das kommt darauf wie "jobs" eingestellt ist. Die Daten der Liste werden bei >1 parallel eingespielt. 

Verstehe. Diesen Parameter habe ich bisher nicht explizit gesetzt, so dass wohl gilt "CPU-Anzahl - 1". Da der Rechner 8 CPUs hat, gilt also "jobs = 7". "jobs = 1" würde also dazu führen, dass die Dateien nacheinander importiert werden.

> Die Reihe kann man dann aber auch mit etwas anderem als einer Datei, Leerzeile oder Kommentar teilen. Dann werden die Teile nacheinander importiert, aber die Dateien darin parallel.

Den Part verstehe ich noch nicht ganz. Können Sie das genauer erläutern? Und vielleicht ein kleines Beispiel geben?

**Comment by mrclBIE** [comment]
Und warum nun "jobs = -1"? Wo ist der Unterschied zu "jobs = 1"?
Kann jobs mehrfach in einer lst Datei angegeben werden?
Funktioniert auch folgende Konfiguration für einen synchronen Import?

````
...
jobs 1
1/1.xml
1/2.xml
1/3.xml
2/1.xml
2/2.xml
3/1.xml
