### ISSUE TITLE
ERROR: null value in relation "ax_grablochderbodenschaetzung" and column "gemarkungsnummer" violates not-null constraint

### ISSUE THREAD

**Issue by FritzHoing** [norBIT/alkisimport#81]
Hello, i am using the gid7 branch to import [ALKIS test data from Niedersachsen](https://www.lgln.niedersachsen.de/startseite/geodaten_karten/afis_alkis_atkis/aaa_testdaten/).

While the import of the basis Data works perfectly fine, i encounter the error when updating the DB using [NBA-data](https://www.lgln.niedersachsen.de/startseite/geodaten_karten/afis_alkis_atkis/alkis/alkis-datenuebermittlung-mit-nba-verfahren-220083.html).

The log can be found here: 
[NBA-log.txt](https://github.com/user-attachments/files/15584336/NBA-log.txt)

I am not sure if the provided NBA-Test data is incorrect or if maybe the not null constraint is wrong in the schema.

**Comment by jef-n** [comment]
Die GID7-Testdaten in Niedersachsen liegen unter https://www.lgln.niedersachsen.de/startseite/geodaten_karten/afis_alkis_atkis/aaa_testdaten/testdaten-220074.html:

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- DHK  533   (DHK  533  106.0.813                      20-Jul-2023 16:02:03) -->
<AX_Bestandsdatenauszug
	xmlns="http://www.adv-online.de/namespaces/adv/gid/7.1"
```

Die Daten unter https://www.lgln.niedersachsen.de/startseite/geodaten_karten/afis_alkis_atkis/alkis/alkis-datenuebermittlung-mit-nba-verfahren-220083.html sind noch GID6:

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- DHK  413   (DHK  413  103.1.364                      23-Nov-2021 07:30:25) -->
<!-- Verzeichnis /opt/vkv/Tomcat_AAA-DHK/webapps/AAA-DHK/libs -->
<!-- Schemadatei /opt/vkv/Tomcat_AAA-DHK/webapps/AAA-DHK/Schemata/Schemata_600/SchemataKunde/NAS-Operationen.xsd -->
<AX_NutzerbezogeneBestandsdatenaktualisierung_NBA
        xmlns="http://www.adv-online.de/namespaces/adv/gid/6.0"
```

**Comment by FritzHoing** [comment]
You are absolutely right! Thank you very much for the quick response and sorry for the misconception.

**Comment by jef-n** [comment]
> You are absolutely right! Thank you very much for the quick response and sorry for the misconception.

Da nicht für
