### ISSUE TITLE
Verwendung von 2 Attributen

### ISSUE THREAD

**Issue by GerhardMuench** [norBIT/alkisimport#85]
Für die Objektart 41002 und die FKT 2500, 2530 und 2570 z.B. sind weitere Attribute PEG 1000 - 7500 zulässig.
Die Tabelle nutz_shl sieht aber nur die FKT1 mit Werteart1 vor.
Ist es möglich eine FKT2 wie PEG mit Werteart2 einzufügen?
Vielen Dank für einen Hint.
Viele Grüße
Gerhard Münch

**Comment by jef-n** [comment]
In nutz21/ nutz_shl finden sich nur die Nutzungen.  Detailiertere Information zu Industrie- und Gewerbeflächen könnte man sich aber aus ax_industrieundgewerbe / ax_{primaerenergie,lagergut,foerdergut,zustand}_industrieundgewerbeflaeche holen.
