### ISSUE TITLE
OSGEO4W installer: Can't open ...src.tar.bz2 for reading: invalid or unsupported tar format

### ISSUE THREAD

**Issue by gregorhd** [norBIT/alkisimport#86]
Bekomme denselben Fehler wie [dieser ](https://gis.stackexchange.com/questions/478206/error-installing-norgis-alkis-importer-package-with-osgeo4w)OP, wenn ich die aktuellen Versionen über die OSGEO4W Distribution installieren will, sowohl für `alkis-import-3.0-62` als auch `alkis-import-gid7-4.1-10`.

`osgeo4w-setup.exe` auch als Administrator gestartet, selbes Ergebnis.

**Comment by jef-n** [comment]
Die Quellen sind in diesem Repositorium.  Die Quellarchive sind leer.

**Comment by gregorhd** [comment]
Danke. Hatte ich auch auch gesehen, und vermutet, da stimme einfach mit dem Download etwas nicht. Wäre es dann nicht hilfreich, den Hinweis auf das Vorhandensein der Pakete in OSGeo4W [auf der Webseite ](https://www.norbit.de/68/) zu aktualisieren?

**Comment by jef-n** [comment]
> Danke. Hatte ich auch auch gesehen, und vermutet, da stimme einfach mit dem Download etwas nicht. Wäre es dann nicht hilfreich, den Hinweis auf das Vorhandensein der Pakete in OSGeo4W [auf der Webseite ](https://www.norbit.de/68/) zu aktualisieren?

Die Möglichkeit die Quellen durch Anhaken der Spalte "Src?" im Installer herunterzuladen ist dort gar nicht erwähnt.
