### ISSUE TITLE
Tabelle ax_georeferenziertegebaeudeadresse leer

### ISSUE THREAD

**Issue by PhilippRedel** [norBIT/alkisimport#88]
Wir haben erfolgreich über den GUI Importer aktuelle NAS Daten nach GeoInfoDok 7.1 importiert.
Die Tabelle ax_georeferenziertegebaeudeadresse ist jedoch nach dem Import leer. 
Wird diese Tabelle grundsätzlich nicht durch den Importer gefüllt oder muss dafür eine andere Einstellung im Importer vorgenommen werden?

Vielen Dank!

**Comment by geoglis** [comment]
Daten aus welchem Bundesland habt ihr denn benutzt? Ganzes BL oder nur einen Teil davon? Welchen Stand haben die Daten?

**Comment by PhilippRedel** [comment]
Die Daten sind aus Bayern und dort nur aus einem Landkreis. Die Daten haben den Stand 02.07.2024 und es traten keine Fehlermeldungen während des Imports auf.

**Comment by geoglis** [comment]
Danke. Und welcher Landkreis?

**Comment by PhilippRedel** [comment]
Die Daten betreffen einen Teil des Landkreises Forchheim in Oberfranken. Einen Link gibt es nicht da ein Teil der Daten keine kostenlos öffentlich zugänglichen sind.

**Comment by geoglis** [comment]
D.h., ihr habt mit nicht frei verfügbaren Daten gearbeitet? Das würde es schwieriger machen, den möglichen Fehler zu finden...

**Comment by geoglis** [comment]
Schau mal bitte nach, ob in den Daten so etwas vorkommt:

```xml
<gml:featureMember>
        <AX_GeoreferenzierteGebaeudeadresse gml:id="DEHHALKAn0004QRq">
          <gml:identifier codeSpace="http://www.adv-online.de/">urn:adv:oid:DEHHALKAn0004QRq</gml:identifier>
          <lebenszeitintervall>
            <AA_Lebenszeitintervall>
              <beginnt>2010-03-05T21:30:05Z</beginnt>
            </AA_Lebenszeitintervall>
          </lebenszeitintervall>
          <modellart>
            <AA_Modellart>
              <advStandardModell>DLKM</advStandardModell>
            </AA_Modellart>
          </modellart>
          <position>
            <gml:Point gml:id="DEHHALKAn0004QRq_G0" srsName="urn:adv:crs:ETRS89_UTM32">
              <gml:pos>577318.943 5917910.609</gml:pos>
            </gml:Point>
          </position>
          <qualitaetsangaben>1000</qualitaetsangaben>
          <land>02</land>
          <regierungsbezirk>0</regierungsbezirk>
          <kreis>00</kreis>
          <gemeinde>000</gemeinde>
          <ortsteil>0</ortsteil>
          <strassenschluessel>K1990</strassenschluessel>
          <hausnummer>170</hausnummer>
          <postalischeAdresse>
            <AX_Post>
              <postleitzahl>21037</postleitzahl>
              <ortsnamePost>Hamburg</ortsnamePost>
              <strassenname>Kirchwerder Elbdeich</strassenname>
            </AX_Post>
          </postalischeAdresse>
          <hatAuch xlink:href="urn:adv:oid:DEHHALKAn0000L46" />
        </AX_GeoreferenzierteGebaeudeadresse>
      </gml:featureMember>
```

**Comment by PhilippRedel** [comment]
Ja die Daten sind leider nicht frei verfügbar.
Und so wie es Aussieht tauchen in den Daten keine "<AX_GeoreferenzierteGebaeudeadresse" auf das heißt der Datensatz den wir haben ist scheinbar unvollständig. Entschuldigung für die Mühe wir sind davon ausgegeangen dass die Datensätze alle standardisierten Infos enthalten und nur der Import nicht klappte.

**Comment by jef-n** [comment]
@PhilippRedel der View v_haeuser ist vielleicht ein Alternative.

**Comment by PhilippRedel** [comment]
> @PhilippRedel der View v_haeuser ist vielleicht ein Alternative.

Das hatte ich auch gedacht die View hat auch daten jedoch sind die spalten strshl und strname sowie gemshl und gemname in allen zeilen null daher kann ich zwar die hausnummer und die koordinaten sehen aber keinen straßennamen.

**Comment by jef-n** [comment]
> > @PhilippRedel der View v_haeuser ist vielleicht ein Alternative.
> 
> Das hatte ich auch gedacht die View hat auch daten jedoch sind die spalten strshl und strname sowie gemshl und gemname in allen zeilen null daher kann ich zwar die hausnummer und die koordinaten sehen aber keinen straßennamen.

Achja, Bayern - keine Straßenschlüssel / ax_lagebezeichnungkatalogeintrag…

```
DROP VIEW v_haeuser;
CREATE OR REPLACE VIEW public.v_haeuser AS
 SELECT foo.ogc_fid,
    foo.point AS wkb_geometry,
    st_x(foo.point) AS x_coord,
    st_y(foo.point) AS y_coord,
    foo.strshl,
    coalesce(str_shl.strname,foo.unverschluesselt) AS strname,
    foo.ha_nr,
    str_shl.gemshl,
    gem_shl.gemname
   FROM ( SELECT g.ogc_fid * 268435456::bigint + o.ogc_fid AS ogc_fid,
            st_centroid(g.wkb_geometry) AS point,
            ((((to_char(alkis_toint(o.land), 'fm00'::text) || o.regierungsbezirk::text) || to_char(alkis_toint(o.kreis), 'fm00'::text)) || to_char(alkis_toint(o.gemeinde), 'fm000'::text)) || '    '::text) || btrim(o.lage::text) AS strshl,
            o.unverschluesselt,
            o.hausnummer AS ha_nr
           FROM ax_lagebezeichnungmithausnummer o
             JOIN ax_gebaeude g ON ARRAY[o.gml_id] <@ g.zeigtauf AND g.endet IS NULL
          WHERE o.endet IS NULL) foo
     LEFT JOIN str_shl USING (strshl)
     LEFT JOIN gem_shl USING (gemshl);
```

**Comment by jef-n** [comment]
> Das angepasste View SQL beinhaltet zwar die Straßennamen, gibt es eine Möglichkeit auch die Gemeinde noch dazu zu verknüpfen da diese auch null ist? Ich bin mit meinen Versuchen das selbst hinzubekommen leider auf keinen Erfolg gestoßen. Vielen Dank!

```
DROP VIEW v_haeuser;
CREATE VIEW v_haeuser AS
  SELECT
    ogc_fid,
    point AS wkb_geometry,
    st_x(point) AS x_coord,
    st_y(point) AS y_coord,
    strshl,
    strname,
    ha_nr,
    gemshl,
    gemname
  FROM (
    SELECT
      g.ogc_fid * 268435456::bigint + o.ogc_fid AS ogc_fid,
      st_centroid(g.wkb_geometry) AS point,
      coalesce(
        to_char(alkis_toint(o.land),'fm00')||o.regierungsbezirk||to_char(alkis_toint(o.kreis),'fm00')||to_char(alkis_toint(o.gemeinde),'fm000')||'    '||trim(o.lage),
        (
          SELECT strshl
          FROM ax_flurstueck f
          JOIN str_shl ON gemshl=to_char(alkis_toint(f.gemeindezugehoerigkeit_land),'fm00')||f.gemeindezugehoerigkeit_regierungsbezirk||to_char(alkis_toint(f.gemeindezugehoerigkeit_kreis),'fm00')||to_char(alkis_toint(f.gemeindezugehoerigkeit_gemeinde),'fm000') AND strname=o.unverschluesselt
          WHERE ARRAY[o.gml_id] <@ f.weistauf AND f.endet IS NULL
          LIMIT 1
       )
      ) AS strshl,
      hausnummer AS ha_nr
    FROM ax_lagebezeichnungmithausnummer o
    JOIN ax_gebaeude g ON ARRAY[o.gml_id] <@ g.zeigtauf AND g.endet IS NULL
    WHERE o.endet IS NULL
  ) AS foo
  LEFT OUTER JOIN str_shl USING (strshl)
  LEFT OUTER JOIN gem_shl USING (gemshl)
;
```
