### ISSUE TITLE
Import only subset of the tables from the whole ALKIS schema

### ISSUE THREAD

**Issue by msochan** [norBIT/alkisimport#89]
Hey guys, maybe somebody already encountered similar problem to mine like I'm trying to import only "ax_flurstueck" table (or in general only subset of the tables) from Hessen state (example file [in the Attachment](https://github.com/user-attachments/files/16815822/431200-Gemarkung-Michelbuch--gemeindefrei-_20240724_1von1_489133_5473312.zip)). 

So I'm specifying that in "tables.lst" file, and then starting running the import. 
Afterwards I find out that also other tables like "ax_gebaeude" etc. were also imported. 

Am I doing something wrong?

**Comment by jef-n** [comment]
Partials imports are not implemented. Shortening `tables.lst` does not help, but adding `ax_flurstueck` (or in general a list of layers) to the `ogr2ogr` call does.

**Comment by msochan** [comment]
@jef-n Thank you for a quick response! Now I'm passing the tables into the ogr2ogr, and it looks like that way, it's working as desired! 🙏
